package Furniture.structure;

/*Generated by MPS */

import jetbrains.mps.smodel.runtime.EnumerationDescriptorBase;
import jetbrains.mps.smodel.runtime.EnumerationDescriptor;
import jetbrains.mps.lang.smodel.EnumerationLiteralsIndex;
import java.util.List;
import org.jetbrains.annotations.Nullable;
import org.jetbrains.annotations.NotNull;

public class EnumerationDescriptor_Material extends EnumerationDescriptorBase {

  public EnumerationDescriptor_Material() {
    super(0x34ef3d3158464526L, 0xae0c0b6af6b7afd7L, 0x5272a355c6b778a2L, "Material", "r:ee1d3842-8e0e-405d-8acf-89b18383bdd9(Furniture.structure)/5940990447256565922");
  }

  private final EnumerationDescriptor.MemberDescriptor myMember_Maple_0 = new EnumerationDescriptor.MemberDescriptor("Maple", "wood", 0x5272a355c6b778a3L, "r:ee1d3842-8e0e-405d-8acf-89b18383bdd9(Furniture.structure)/5940990447256565923");
  private final EnumerationDescriptor.MemberDescriptor myMember_Oak_0 = new EnumerationDescriptor.MemberDescriptor("Oak", "metal", 0x5272a355c6b778a8L, "r:ee1d3842-8e0e-405d-8acf-89b18383bdd9(Furniture.structure)/5940990447256565928");
  private final EnumerationDescriptor.MemberDescriptor myMember_Iron_0 = new EnumerationDescriptor.MemberDescriptor("Iron", "iron", 0x5272a355c6b778b1L, "r:ee1d3842-8e0e-405d-8acf-89b18383bdd9(Furniture.structure)/5940990447256565937");
  private final EnumerationDescriptor.MemberDescriptor myMember_Steel_0 = new EnumerationDescriptor.MemberDescriptor("Steel", "steel", 0x5272a355c6b778b5L, "r:ee1d3842-8e0e-405d-8acf-89b18383bdd9(Furniture.structure)/5940990447256565941");

  private final EnumerationLiteralsIndex myIndex = EnumerationLiteralsIndex.build(0x34ef3d3158464526L, 0xae0c0b6af6b7afd7L, 0x5272a355c6b778a2L, 0x5272a355c6b778a3L, 0x5272a355c6b778a8L, 0x5272a355c6b778b1L, 0x5272a355c6b778b5L);
  private final List<EnumerationDescriptor.MemberDescriptor> myMembers = new EnumerationDescriptorBase.MembersList(myIndex, myMember_Maple_0, myMember_Oak_0, myMember_Iron_0, myMember_Steel_0);

  @Nullable
  @Override
  public EnumerationDescriptor.MemberDescriptor getDefault() {
    return myMember_Steel_0;
  }

  @NotNull
  @Override
  public List<EnumerationDescriptor.MemberDescriptor> getMembers() {
    return myMembers;
  }

  @Nullable
  @Override
  public EnumerationDescriptor.MemberDescriptor getMember(@Nullable String memberName) {
    if (memberName == null) {
      return null;
    }
    switch (memberName) {
      case "Maple":
        return myMember_Maple_0;
      case "Oak":
        return myMember_Oak_0;
      case "Iron":
        return myMember_Iron_0;
      case "Steel":
        return myMember_Steel_0;
    }
    return null;
  }

  @Nullable
  @Override
  public EnumerationDescriptor.MemberDescriptor getMember(long idValue) {
    int index = myIndex.index(idValue);
    if (index == -1) {
      return null;
    }
    return myMembers.get(index);
  }
}
