package HTML.textGen;

/*Generated by MPS */

import jetbrains.mps.text.rt.TextGenDescriptorBase;
import jetbrains.mps.text.rt.TextGenContext;
import jetbrains.mps.text.impl.TextGenSupport;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SLinkOperations;
import org.jetbrains.mps.openapi.language.SContainmentLink;
import jetbrains.mps.smodel.adapter.structure.MetaAdapterFactory;

public class HtmlFile_TextGen extends TextGenDescriptorBase {
  @Override
  public void generateText(final TextGenContext ctx) {
    final TextGenSupport tgs = new TextGenSupport(ctx);
    tgs.appendNode(SLinkOperations.getTarget(ctx.getPrimaryInput(), LINKS.document$Qvdu));
  }

  private static final class LINKS {
    /*package*/ static final SContainmentLink document$Qvdu = MetaAdapterFactory.getContainmentLink(0xce78ae2cdb1f49adL, 0xbab2413b7d7689f5L, 0x19f6196be705fb5fL, 0x19f6196be705fb62L, "document");
  }
}
